import React, { Component } from 'react';
import HomeScreen from './components/HomeScreen';
import JobScreen from './components/JobScreen';
import ReviewForm from './components/ReviewForm';
import logo from './logo.svg';
import './App.css';

import firebase from 'firebase';

// Initialize Firebase
var firebaseConfig = {
  apiKey: "AIzaSyD26AQhzl73lJeBzGZ4EsSOKcpICv2FA1o",
  authDomain: "purplewindow-3acf0.firebaseapp.com",
  databaseURL: "https://purplewindow-3acf0.firebaseio.com",
  projectId: "purplewindow-3acf0",
  storageBucket: "purplewindow-3acf0.appspot.com",
  messagingSenderId: "794968149806"
};
firebase.initializeApp(firebaseConfig);

const db = firebase.database();
// const ref = db.ref("purplewindow-3acf0");

const JOBS = [
  {
      "title": "Education and Social Policy Research Aide",
      "employer": "NU Education and Social Policy Department",
      "website": "https://www.sesp.northwestern.edu/",
      "rating": 4.6,
      "pay": "$11.10/hr",
      "tags": ["Fisk Hall", "Undergrad", "SESP"],
      "hours": "8 to 10",
      "apply": null,
      "contact": "Adrienne Hu",
      "email": "sihua.hu@northwestern.edu",
      "phone": "847-467-6265",
      "description": "The Research Aide will provide research and administrative support for several studies related to educational policy conducted by Professor Cynthia Coburn. This position begins in Spring 2019, with the possibility to renew. Duties include: coding interview transcripts and surveys, entering data into qualitative and quantitative software programs, reviewing literature, and performing other administrative duties.",
      "qualifications": "Qualified students are reliable, organized, able to work independently, and detail oriented with a background in education, sociology, or organizational change. We are especially interested in hiring students who are able to stay on longer than one quarter.",
      "workStudy": true,
      "onCampus": true,
      "reviews": [
          {
              "id": 1,
              "title": "Fancy from the outside",
              "date": 20190402,
              "recommend": false,
              "outlook": "neutral",
              "ceoOpinion": null,
              "balance": 2,
              "culture": 1,
              "careerOpps": 4,
              "benefits": 3,
              "mgmt": 3,
              "total": 3,
              "pros": "The name alone will get you in the door to other jobs",
              "cons": "Your role, opinion are not valued, pay is low compared to similar institutions. They depend on their name as compensation, but if your a real professional you contribute as much as they do and you should be compensated as such. No diversity, nonfriendly culture throughout every department.",
              "advice": null,
              "currentEmployee": false,
              "fullTime": false,
              "tenure": "<1",
              "role": "Nurse Clinician",
              "locationCity": "Chicago",
              "locationState": "IL",
          },

          {
              "id": 2,
              "title": "Great place to research!",
              "date": 20190404,
              "recommend": true,
              "outlook": "positive",
              "ceoOpinion": null,
              "balance": 5,
              "culture": 5,
              "careerOpps": 5,
              "benefits": 5,
              "mgmt": 5,
              "total": 5,
              "pros": "This is a great place to get a degree. Community is very supportive and encourages you to learn.",
              "cons": "Winters can be a bit rough being in Chicago, but that's true of every company here.",
              "advice": null,
              "currentEmployee": true,
              "fullTime": true,
              "tenure": ">5",
              "role": "PhD Candidate",
              "locationCity": "Chicago",
              "locationState": "IL",
          },

          {
              "id": 3,
              "title": "Great College Job",
              "date": 20150430,
              "recommend": true,
              "outlook": "positive",
              "ceoOpinion": null,
              "balance": 5,
              "culture": 5,
              "careerOpps": 5,
              "benefits": 5,
              "mgmt": 5,
              "total": 5,
              "pros": "Great experience, great resume builder. This job allows you to be able to put quantifiable accomplishments on your resume. Offers promotions to grow.",
              "cons": "Sometimes being a caller may get boring or tiring. Every once in a while you will speak to a grumpy alum that might ruin your day, but this does not happen that often.",
              "advice": "Keep trying to improve the program as best as you can. Make sure to keep work environment fun and uplifting. Keep finding novel ways to keep room moral high.",
              "currentEmployee": true,
              "fullTime": false,
              "tenure": null,
              "role": null,
              "locationCity": null,
              "locationState": null,
        },

        {
              "id": 4,
              "title": "Great work experience",
              "date": 20141208,
              "recommend": true,
              "outlook": "positive",
              "ceoOpinion": null,
              "balance": 5,
              "culture": 5,
              "careerOpps": 5,
              "benefits": 4,
              "mgmt": 5,
              "total": 5,
              "pros": "Supportive management, exciting goals, many learning opportunities and potential for growth",
              "cons": "It's a big department, so it can be hard to get to know everyone. Stand out by making a name for yourself through solid work ethic and networking",
              "advice": null,
              "currentEmployee": true,
              "fullTime": true,
              "tenure": ">3",
              "role": "Associate Director",
              "locationCity": null,
              "locationState": null,
        },

        {
              "id": 5,
              "title": "Good part time job",
              "date": 20190318,
              "recommend": null,
              "outlook": null,
              "ceoOpinion": null,
              "balance": null,
              "culture": null,
              "careerOpps": null,
              "benefits": null,
              "mgmt": null,
              "total": 5,
              "pros": "Good balance and understanding of other priorities",
              "cons": "tasks were tedious and sometimes felt like they had little impact, but have to be done",
              "advice": null,
              "currentEmployee": false,
              "fullTime": false,
              "tenure": ">1",
              "role": "Student Worker",
              "locationCity": null,
              "locationState": null,
        },
      ]
  },

  {
      "title": "McCormick Research Aide",
      "employer": "NU McCormick School of Engineering",
      "website": "https://www.mccormick.northwestern.edu/",
      "rating": 3.8,
      "pay": "$12.25/hr",
      "tags": ["Fisk Hall", "Undergrad", "SESP"],
      "hours": null,
      "apply": null,
      "contact": "Eric Masanet",
      "email": "eric.masanet@northwestern.edu",
      "phone": "847-467-2806",
      "description": "Do you have a passion for sustainability, enjoy working with data and spreadsheets, and want to contribute to reducing global energy use? If so, read on! I'm looking for one or more student researchers to compile data on societal materials flows and materials processing technologies, and to build spreadsheets to calculate key inputs into a modeling platform for evaluating policies and strategies for reducing nation/global materials use.",
      "qualifications": "Experience working with large datasets and building well-organized spreadsheets; familiarity with basic energy/environmental concepts, units, and terms; familiarity with materials end uses (e.g., buildings, infrastructure, vehicles); demonstrated analytical skills (e.g., through coursework or projects); strong work ethic; ability to work independently and in teams; ideal for engineering students, but students from other quantitative domains may be considered.",
      "workStudy": true,
      "onCampus": true,
      "reviews": [
          {
              "id": 1,
              "title": "Fancy from the outside",
              "date": 20190402,
              "recommend": false,
              "outlook": "neutral",
              "ceoOpinion": null,
              "balance": 2,
              "culture": 1,
              "careerOpps": 4,
              "benefits": 3,
              "mgmt": 3,
              "total": 1,
              "pros": "The name alone will get you in the door to other jobs",
              "cons": "Your role, opinion are not valued, pay is low compared to similar institutions. They depend on their name as compensation, but if your a real professional you contribute as much as they do and you should be compensated as such. No diversity, nonfriendly culture throughout every department.",
              "advice": null,
              "currentEmployee": false,
              "fullTime": false,
              "tenure": "<1",
              "role": "Nurse Clinician",
              "locationCity": "Chicago",
              "locationState": "IL",
          },

          {
              "id": 2,
              "title": "Great place to research!",
              "date": 20190404,
              "recommend": true,
              "outlook": "positive",
              "ceoOpinion": null,
              "balance": 5,
              "culture": 5,
              "careerOpps": 5,
              "benefits": 5,
              "mgmt": 5,
              "total": 5,
              "pros": "This is a great place to get a degree. Community is very supportive and encourages you to learn.",
              "cons": "Winters can be a bit rough being in Chicago, but that's true of every company here.",
              "advice": null,
              "currentEmployee": true,
              "fullTime": true,
              "tenure": ">5",
              "role": "PhD Candidate",
              "locationCity": "Chicago",
              "locationState": "IL",
          },
      ]
  },

    {
      "title": "Portuguese Tutor Aide",
      "employer": "NU Department of Spanish and Portuguese",
      "website": "https://www.spanish-portuguese.northwestern.edu/",
      "rating": 2.7,
      "pay": "$11.55/hr",
      "tags": ["Fisk Hall", "Undergrad", "SESP"],
      "hours": "3 to 4",
      "apply": null,
      "contact": "Elisa Baena",
      "email": "e-baena@northwestern.edu",
      "phone": "847-491-8220",
      "description": "For the 2018-19 academic year, 3-4 hours a week tutoring Portuguese language students. This includes grammar explanations and practice as well as conversational practice. Please send a letter of interest, resume and a writing sample to the Coordinator of the Portuguese language program, Elisa Baena.",
      "qualifications": "Candidates should have native or near-native proficiency in Portuguese and be responsible, punctual, flexible, helpful and outgoing.",
      "workStudy": true,
      "onCampus": true,
      "reviews": [
          {
              "id": 1,
              "title": "Fancy from the outside",
              "date": 20190402,
              "recommend": false,
              "outlook": "neutral",
              "ceoOpinion": null,
              "balance": 2,
              "culture": 1,
              "careerOpps": 4,
              "benefits": 3,
              "mgmt": 3,
              "total": 1,
              "pros": "The name alone will get you in the door to other jobs",
              "cons": "Your role, opinion are not valued, pay is low compared to similar institutions. They depend on their name as compensation, but if your a real professional you contribute as much as they do and you should be compensated as such. No diversity, nonfriendly culture throughout every department.",
              "advice": null,
              "currentEmployee": false,
              "fullTime": false,
              "tenure": "<1",
              "role": "Nurse Clinician",
              "locationCity": "Chicago",
              "locationState": "IL",
          },

          {
              "id": 2,
              "title": "Great place to research!",
              "date": 20190404,
              "recommend": true,
              "outlook": "positive",
              "ceoOpinion": null,
              "balance": 5,
              "culture": 5,
              "careerOpps": 5,
              "benefits": 5,
              "mgmt": 5,
              "total": 5,
              "pros": "This is a great place to get a degree. Community is very supportive and encourages you to learn.",
              "cons": "Winters can be a bit rough being in Chicago, but that's true of every company here.",
              "advice": null,
              "currentEmployee": true,
              "fullTime": true,
              "tenure": ">5",
              "role": "PhD Candidate",
              "locationCity": "Chicago",
              "locationState": "IL",
          },
      ]
  },

    {
      "title": "Entrance Desk Assistant",
      "employer": "NU Facilities Operations & Security Management",
      "website": "https://www.northwestern.edu/fm/index.html",
      "rating": 3.3,
      "pay": "$11.10/hr",
      "tags": ["Fisk Hall", "Undergrad", "SESP"],
      "hours": "12 to 20",
      "apply": "https://www.library.northwestern.edu/about/library-jobs/student-jobs/index.html",
      "contact": null,
      "email": "library-personnel@northwestern.edu",
      "phone": "847-491-7668",
      "description": "Providing a welcoming, friendly and professional presence at the entrance to Deering Library and the Main Library. Ensuring the best customer service to all patrons. Answering patron questions and referring them to appropriate departments within the library. Explaining library access policies. Ensuring that all library materials are properly checked out as patrons leave the building. Directing patrons to the appropriate areas as needed. To ensure absolute privacy on sensitive material. Ability to clearly communicate. Possess time management skills.",
      "qualifications": "We are looking for someone who is available for all of Spring, Summer, Fall, and Winter quarters. An ideal candidate would be a graduate student who has finished their course work. We are looking for someone who is willing to learn, appreciate, and deliver great customer service to all patrons. The ability to work well with all faculty, staff, students, alumni, and visitors. We are also looking for someone who can communicate clearly, to all patrons, the policies of the libraries. Must be friendly, helpful, alert, and a self-motivated person who illustrates professionalism. Experience working with the public or any customer service is preferred but not required. The ability to lift 20 pounds of library materials.",
      "workStudy": false,
      "onCampus": true,
      "reviews": [
          {
              "id": 1,
              "title": "Fancy from the outside",
              "date": 20190402,
              "recommend": false,
              "outlook": "neutral",
              "ceoOpinion": null,
              "balance": 2,
              "culture": 1,
              "careerOpps": 4,
              "benefits": 3,
              "mgmt": 3,
              "total": 1,
              "pros": "The name alone will get you in the door to other jobs",
              "cons": "Your role, opinion are not valued, pay is low compared to similar institutions. They depend on their name as compensation, but if your a real professional you contribute as much as they do and you should be compensated as such. No diversity, nonfriendly culture throughout every department.",
              "advice": null,
              "currentEmployee": false,
              "fullTime": false,
              "tenure": "<1",
              "role": "Nurse Clinician",
              "locationCity": "Chicago",
              "locationState": "IL",
          },

          {
              "id": 2,
              "title": "Great place to research!",
              "date": 20190404,
              "recommend": true,
              "outlook": "positive",
              "ceoOpinion": null,
              "balance": 5,
              "culture": 5,
              "careerOpps": 5,
              "benefits": 5,
              "mgmt": 5,
              "total": 5,
              "pros": "This is a great place to get a degree. Community is very supportive and encourages you to learn.",
              "cons": "Winters can be a bit rough being in Chicago, but that's true of every company here.",
              "advice": null,
              "currentEmployee": true,
              "fullTime": true,
              "tenure": ">5",
              "role": "PhD Candidate",
              "locationCity": "Chicago",
              "locationState": "IL",
          },
      ]
  },

    {
      "title": "Text Digitization Aide",
      "employer": "NU Repository & Digital Curation",
      "website": "https://www.library.northwestern.edu/",
      "rating": 2.1,
      "pay": "$11.55/hr",
      "tags": ["Fisk Hall", "Undergrad", "SESP"],
      "hours": "8 to 12",
      "apply": "https://www.library.northwestern.edu/about/library-jobs/student-jobs/index.html",
      "contact": null,
      "email": "library-personnel@northwestern.edu",
      "phone": "847-491-7668",
      "description": "This job involves considerable responsibilities digitizing library materials for online use by students, faculty and others. You will perform image processing of scanned files. In this interesting, project-oriented environment, you should be able to perform repetitive tasks with great accuracy and productivity. Assignments will include some of the following: image editing, document inventory, and document mark-up. The job also involves tracking the original documents and their digitized files, as well as quality review of scanned items. Tasks may also include trouble-shooting and helping to document procedures in a developing workflow system. Other duties may be assigned as needed.",
      "qualifications": "A great degree of personal responsibility, independence, consistency and attention to detail are required. Required experience: image processing in Photoshop or other application; word processing; spreadsheets. Experience with any of the following is desirable: photography, digital imaging, HTML authoring.",
      "workStudy": false,
      "onCampus": true,
      "reviews": [
          {
              "id": 1,
              "title": "Fancy from the outside",
              "date": 20190402,
              "recommend": false,
              "outlook": "neutral",
              "ceoOpinion": null,
              "balance": 2,
              "culture": 1,
              "careerOpps": 4,
              "benefits": 3,
              "mgmt": 3,
              "total": 1,
              "pros": "The name alone will get you in the door to other jobs",
              "cons": "Your role, opinion are not valued, pay is low compared to similar institutions. They depend on their name as compensation, but if your a real professional you contribute as much as they do and you should be compensated as such. No diversity, nonfriendly culture throughout every department.",
              "advice": null,
              "currentEmployee": false,
              "fullTime": false,
              "tenure": "<1",
              "role": "Nurse Clinician",
              "locationCity": "Chicago",
              "locationState": "IL",
          },

          {
              "id": 2,
              "title": "Great place to research!",
              "date": 20190404,
              "recommend": true,
              "outlook": "positive",
              "ceoOpinion": null,
              "balance": 5,
              "culture": 5,
              "careerOpps": 5,
              "benefits": 5,
              "mgmt": 5,
              "total": 5,
              "pros": "This is a great place to get a degree. Community is very supportive and encourages you to learn.",
              "cons": "Winters can be a bit rough being in Chicago, but that's true of every company here.",
              "advice": null,
              "currentEmployee": true,
              "fullTime": true,
              "tenure": ">5",
              "role": "PhD Candidate",
              "locationCity": "Chicago",
              "locationState": "IL",
          },
      ]
  },

    {
      "title": "University Archives Audio Tour Aide",
      "employer": "NU Distinctive Collections: University Archives",
      "website": "https://www.library.northwestern.edu/",
      "rating": 3.9,
      "pay": "$11.25/hr",
      "tags": ["Fisk Hall", "Undergrad", "SESP"],
      "hours": "At least 8",
      "apply": "https://www.library.northwestern.edu/about/library-jobs/student-jobs/index.html",
      "contact": null,
      "email": "library-personnel@northwestern.edu",
      "phone": "847-491-7668",
      "description": "Work with the Archivist for the Black Experience to identify historically significant places to the history of the black student experience at Northwestern. Draw upon archival documents to draft a script describing the history of each identified location. Then create an audio recording of the tour.",
      "qualifications": "-Excellent research, writing, and analytical skills; -Interest in Northwestern history, public history, African American history, and working with archival material; -Knowledge of the history of the Bursar’s Office Takeover, a plus; -Attention to detail, reliable, and organized; -Able to work independently; -Knowledge of audio editing software (ex. Audacity) and experience using a vocal booth is a plus, but not required. This position is open to enrolled undergraduate and graduate students, or recent graduates.",
      "workStudy": true,
      "onCampus": true,
      "reviews": [
          {
              "id": 1,
              "title": "Fancy from the outside",
              "date": 20190402,
              "recommend": false,
              "outlook": "neutral",
              "ceoOpinion": null,
              "balance": 2,
              "culture": 1,
              "careerOpps": 4,
              "benefits": 3,
              "mgmt": 3,
              "total": 1,
              "pros": "The name alone will get you in the door to other jobs",
              "cons": "Your role, opinion are not valued, pay is low compared to similar institutions. They depend on their name as compensation, but if your a real professional you contribute as much as they do and you should be compensated as such. No diversity, nonfriendly culture throughout every department.",
              "advice": null,
              "currentEmployee": false,
              "fullTime": false,
              "tenure": "<1",
              "role": "Nurse Clinician",
              "locationCity": "Chicago",
              "locationState": "IL",
          },

          {
              "id": 2,
              "title": "Great place to research!",
              "date": 20190404,
              "recommend": true,
              "outlook": "positive",
              "ceoOpinion": null,
              "balance": 5,
              "culture": 5,
              "careerOpps": 5,
              "benefits": 5,
              "mgmt": 5,
              "total": 5,
              "pros": "This is a great place to get a degree. Community is very supportive and encourages you to learn.",
              "cons": "Winters can be a bit rough being in Chicago, but that's true of every company here.",
              "advice": null,
              "currentEmployee": true,
              "fullTime": true,
              "tenure": ">5",
              "role": "PhD Candidate",
              "locationCity": "Chicago",
              "locationState": "IL",
          },
      ]
  },

    {
      "title": "Library Receiving Aide",
      "employer": "NU Business & Receiving",
      "website": "https://www.library.northwestern.edu/",
      "rating": 1.7,
      "pay": "$11.25/hr",
      "tags": ["Fisk Hall", "Undergrad", "SESP"],
      "hours": "3 hours a day, 5 days a week",
      "apply": "https://www.library.northwestern.edu/about/library-jobs/student-jobs/index.html",
      "contact": null,
      "email": "library-personnel@northwestern.edu",
      "phone": "847-491-7668",
      "description": "The primary responsibility of this position is to assist the Receiving Office with basic operational tasks such as: • Scan all incoming mail (FedEx, UPS, DHL and USPS) and log packages to appropriate folders on PC. • Email departments/staff to pick up packages. • Deliver and pick up books from circulation and sort them to appropriate destination tubs. • Help direct traffic that goes through Receiving Room (e.g. contractors, vendors and faculty). • On occasions make deliveries to other offices in the library and outside of the library. • Handle basic receiving questions from staff. • Use the Microsoft Office Suite (Word, Excel, PowerPoint) to enter receiving and/or business data. • Other duties as assigned. The Receiving Office is part of the Business & Receiving Department so this individual may also be asked to assist with some minor business related tasks such as assisting the Business Office with scanning and organizing documents to move from paper to electronic files.",
      "qualifications": "Responsible, self-starting, organized, detail-oriented, able to stay on task, good communication and clerical skills and working knowledge of the Microsoft Office Suite (Word, Excel, PowerPoint). Enjoy working with the public. Punctuality, reliability and attention to details are a must. Must be able to lift a minimum of 40 pounds.",
      "workStudy": true,
      "onCampus": true,
      "reviews": [
          {
              "id": 1,
              "title": "Fancy from the outside",
              "date": 20190402,
              "recommend": false,
              "outlook": "neutral",
              "ceoOpinion": null,
              "balance": 2,
              "culture": 1,
              "careerOpps": 4,
              "benefits": 3,
              "mgmt": 3,
              "total": 1,
              "pros": "The name alone will get you in the door to other jobs",
              "cons": "Your role, opinion are not valued, pay is low compared to similar institutions. They depend on their name as compensation, but if your a real professional you contribute as much as they do and you should be compensated as such. No diversity, nonfriendly culture throughout every department.",
              "advice": null,
              "currentEmployee": false,
              "fullTime": false,
              "tenure": "<1",
              "role": "Nurse Clinician",
              "locationCity": "Chicago",
              "locationState": "IL",
          },

          {
              "id": 2,
              "title": "Great place to research!",
              "date": 20190404,
              "recommend": true,
              "outlook": "positive",
              "ceoOpinion": null,
              "balance": 5,
              "culture": 5,
              "careerOpps": 5,
              "benefits": 5,
              "mgmt": 5,
              "total": 5,
              "pros": "This is a great place to get a degree. Community is very supportive and encourages you to learn.",
              "cons": "Winters can be a bit rough being in Chicago, but that's true of every company here.",
              "advice": null,
              "currentEmployee": true,
              "fullTime": true,
              "tenure": ">5",
              "role": "PhD Candidate",
              "locationCity": "Chicago",
              "locationState": "IL",
          },
      ]
  },

    {
      "title": "Print Collections Assistant",
      "employer": "NU Print Collection Management",
      "website": "https://www.library.northwestern.edu/",
      "rating": 2.8,
      "pay": "$11.10/hr",
      "tags": ["Fisk Hall", "Undergrad", "SESP"],
      "hours": "8 to 12",
      "apply": "https://www.library.northwestern.edu/about/library-jobs/student-jobs/index.html",
      "contact": null,
      "email": "library-personnel@northwestern.edu",
      "phone": "847-491-7668",
      "description": "You will retrieve/pull items for the following: Oak Grove Library Center, Interlibrary Loan, NU patron requests, Bindery, Shifting collections, Missing item searches. Shelving duties will include: Sorting, Shelving across all collections including Deering and Main, Shelf-reading, Scanning in material with Alma, Shifting projects. Other duties as assigned.",
      "qualifications": "Responsible, self-starting, organized, detail-oriented, communicative, able to stay on task and navigate multiple systems with minimal supervision. Must be able to lift a minimum of 10 pounds and push/pull a full book cart through the library stacks. Previous library experience preferred. NU students able to work at least one (1) year preferred.",
      "workStudy": false,
      "onCampus": true,
      "reviews": [
          {
              "id": 1,
              "title": "Fancy from the outside",
              "date": 20190402,
              "recommend": false,
              "outlook": "neutral",
              "ceoOpinion": null,
              "balance": 2,
              "culture": 1,
              "careerOpps": 4,
              "benefits": 3,
              "mgmt": 3,
              "total": 1,
              "pros": "The name alone will get you in the door to other jobs",
              "cons": "Your role, opinion are not valued, pay is low compared to similar institutions. They depend on their name as compensation, but if your a real professional you contribute as much as they do and you should be compensated as such. No diversity, nonfriendly culture throughout every department.",
              "advice": null,
              "currentEmployee": false,
              "fullTime": false,
              "tenure": "<1",
              "role": "Nurse Clinician",
              "locationCity": "Chicago",
              "locationState": "IL",
          },

          {
              "id": 2,
              "title": "Great place to research!",
              "date": 20190404,
              "recommend": true,
              "outlook": "positive",
              "ceoOpinion": null,
              "balance": 5,
              "culture": 5,
              "careerOpps": 5,
              "benefits": 5,
              "mgmt": 5,
              "total": 5,
              "pros": "This is a great place to get a degree. Community is very supportive and encourages you to learn.",
              "cons": "Winters can be a bit rough being in Chicago, but that's true of every company here.",
              "advice": null,
              "currentEmployee": true,
              "fullTime": true,
              "tenure": ">5",
              "role": "PhD Candidate",
              "locationCity": "Chicago",
              "locationState": "IL",
          },
      ]
  },

    {
      "title": "NUL Security Student Assistant",
      "employer": "NU Facilities Operations & Security Management",
      "website": "https://www.northwestern.edu/fm/index.html",
      "rating": 3.0,
      "pay": "$12.00/hr",
      "tags": ["Fisk Hall", "Undergrad", "SESP"],
      "hours": "10 to 20",
      "apply": "https://www.library.northwestern.edu/about/library-jobs/student-jobs/index.html",
      "contact": null,
      "email": "library-personnel@northwestern.edu",
      "phone": "847-491-7668",
      "description": "• Provides continuous foot patrol of the Northwestern University Library facility including stairwells, stacks, and public/staff areas to ensure the safety and security of the libraries. • Respond immediately to calls/pages for security response. Answer alarms and investigate disturbances. Maintain good rapport with University Police. Check doors, clear floors, and secure all zones at closing. • Check for facility maintenance problems and unlawful acts or infractions of Library and/or University policies. • Enforce libraries building policy. Report security issues to supervisor or University Police. Handle emergency situations in a calm and controlled manner. Ability to maintain privacy of materials within the libraries. • Prepare/submit detailed security incident reports in email format. Communicate with staff/student assistants on a daily basis to notify them of security issues. Responsible for a high degree of public contact/interaction, such as giving directions and assistance, providing escorts, and circulating among patrons. • Responsible for a high degree of public contact/interaction, such as giving directions and assistance, providing escorts, and circulating among patrons. Unlocking doors, allowing access, and approaching inappropriate patrons. • Must take a proactive approach to enforcing all Library policies and preventing infractions. • Responsible for opening or closing the libraries on a daily basis. Coordinates schedule with other student security assistants to cover missing shifts. Opportunity for picking up additional hours by filling in for other student security assistants.",
      "qualifications": "Non-NU or NU Graduate Student. Works additional hours, when needed. Must be able to work some overnight shifts during reading/finals week. Must be able to adjust work schedule to coincide with Library hours of operation.",
      "workStudy": false,
      "onCampus": true,
      "reviews": [
          {
              "id": 1,
              "title": "Fancy from the outside",
              "date": 20190402,
              "recommend": false,
              "outlook": "neutral",
              "ceoOpinion": null,
              "balance": 2,
              "culture": 1,
              "careerOpps": 4,
              "benefits": 3,
              "mgmt": 3,
              "total": 1,
              "pros": "The name alone will get you in the door to other jobs",
              "cons": "Your role, opinion are not valued, pay is low compared to similar institutions. They depend on their name as compensation, but if your a real professional you contribute as much as they do and you should be compensated as such. No diversity, nonfriendly culture throughout every department.",
              "advice": null,
              "currentEmployee": false,
              "fullTime": false,
              "tenure": "<1",
              "role": "Nurse Clinician",
              "locationCity": "Chicago",
              "locationState": "IL",
          },

          {
              "id": 2,
              "title": "Great place to research!",
              "date": 20190404,
              "recommend": true,
              "outlook": "positive",
              "ceoOpinion": null,
              "balance": 5,
              "culture": 5,
              "careerOpps": 5,
              "benefits": 5,
              "mgmt": 5,
              "total": 5,
              "pros": "This is a great place to get a degree. Community is very supportive and encourages you to learn.",
              "cons": "Winters can be a bit rough being in Chicago, but that's true of every company here.",
              "advice": null,
              "currentEmployee": true,
              "fullTime": true,
              "tenure": ">5",
              "role": "PhD Candidate",
              "locationCity": "Chicago",
              "locationState": "IL",
          },
      ]
  },

    {
      "title": "Lifeguard",
      "employer": "YMCA",
      "website": "http://www.mcgawymca.org/",
      "rating": 3.3,
      "pay": "$11.00/hr to $12.50/hr",
      "tags": ["Fisk Hall", "Undergrad", "SESP"],
      "hours": "Up to 15",
      "apply": null,
      "contact": "Jeanette Hollingsworth",
      "email": "Jeanetteh@mcgawymca.org",
      "phone": "847-475-7400 ext. 271",
      "description": "The lifeguard is responsible for ensuring the safety of the facility patrons by preventing and responding to emergencies as well as enforcing all facility rules and regulations. Monthly mandatory staff meetings are required.",
      "qualifications": "Lifeguards must have basic computer skills, be able to respond to email communication, and be able to complete online testing when required. Must have appropriate certifications (lifeguarding, CPR, FA). Must be ARC lifeguard certified and be able to swim 200 yards each of the following strokes without stopping: Front Crawl, Breaststroke; 150 yards choice (breaststroke/freestyle) Approach stroke 15 yards retrieve 10 lb brick at bottom of pool and return to start point. Tread water for 5 minutes.",
      "workStudy": true,
      "onCampus": false,
      "reviews": [
          {
              "id": 1,
              "title": "Fancy from the outside",
              "date": 20190402,
              "recommend": false,
              "outlook": "neutral",
              "ceoOpinion": null,
              "balance": 2,
              "culture": 1,
              "careerOpps": 4,
              "benefits": 3,
              "mgmt": 3,
              "total": 1,
              "pros": "The name alone will get you in the door to other jobs",
              "cons": "Your role, opinion are not valued, pay is low compared to similar institutions. They depend on their name as compensation, but if your a real professional you contribute as much as they do and you should be compensated as such. No diversity, nonfriendly culture throughout every department.",
              "advice": null,
              "currentEmployee": false,
              "fullTime": false,
              "tenure": "<1",
              "role": "Nurse Clinician",
              "locationCity": "Chicago",
              "locationState": "IL",
          },

          {
              "id": 2,
              "title": "Great place to research!",
              "date": 20190404,
              "recommend": true,
              "outlook": "positive",
              "ceoOpinion": null,
              "balance": 5,
              "culture": 5,
              "careerOpps": 5,
              "benefits": 5,
              "mgmt": 5,
              "total": 5,
              "pros": "This is a great place to get a degree. Community is very supportive and encourages you to learn.",
              "cons": "Winters can be a bit rough being in Chicago, but that's true of every company here.",
              "advice": null,
              "currentEmployee": true,
              "fullTime": true,
              "tenure": ">5",
              "role": "PhD Candidate",
              "locationCity": "Chicago",
              "locationState": "IL",
          },
      ]
  },

    {
      "title": "Program Assistant",
      "employer": "Metrosquash Evanston",
      "website": "http://metrosquash.org/",
      "rating": 0.5,
      "pay": "$11.00/hr",
      "tags": ["Fisk Hall", "Undergrad", "SESP"],
      "hours": null,
      "apply": null,
      "contact": "Claudia Larrea",
      "email": "claudia@metrosquash.org",
      "phone": null,
      "description": "MetroSquash is an after-school, weekend, and summer program that provides transformative, life changing opportunities for underserved youth. The Program Assistant will support the MetroSquash Evanston team in building a preeminent program fully reflective of MetroSquash values and expectations. The position will report to and be supported by the Evanston Program Director. Responsibilities: Recruit, retain, and inspire a cohort of 20 6th grade students with demonstrated need from two partner schools; Plan, support, and implement Evanston after-school programming; Implement measurement systems aligned with current MetroSquash outcomes to assess and demonstrate program effectiveness; Collaborate with MetroSquash staff and leadership to help foster a fully integrated approach to academic, athletic, and wellness development for each student; Program hours are Monday through Friday, 11am - 7pm.",
      "qualifications": "Preferred qualities: Excellent interpersonal, multicultural, and communications skills; impeccable attention to detail and work ethic; self-motivation and the ability to manage multiple projects simultaneously. Valid driver's license and ability to drive a van is a plus but not mandatory. Preferred qualifications: Experience working with youth and their families from underserved and underrepresented communities; Microsoft Office and Google Suite proficiency. If interested, please submit a resume and cover letter, including available start date and preferred hours, to the email listed below.",
      "workStudy": true,
      "onCampus": false,
      "reviews": [
          {
              "id": 1,
              "title": "Fancy from the outside",
              "date": 20190402,
              "recommend": false,
              "outlook": "neutral",
              "ceoOpinion": null,
              "balance": 2,
              "culture": 1,
              "careerOpps": 4,
              "benefits": 3,
              "mgmt": 3,
              "total": 1,
              "pros": "The name alone will get you in the door to other jobs",
              "cons": "Your role, opinion are not valued, pay is low compared to similar institutions. They depend on their name as compensation, but if your a real professional you contribute as much as they do and you should be compensated as such. No diversity, nonfriendly culture throughout every department.",
              "advice": null,
              "currentEmployee": false,
              "fullTime": false,
              "tenure": "<1",
              "role": "Nurse Clinician",
              "locationCity": "Chicago",
              "locationState": "IL",
          },

          {
              "id": 2,
              "title": "Great place to research!",
              "date": 20190404,
              "recommend": true,
              "outlook": "positive",
              "ceoOpinion": null,
              "balance": 5,
              "culture": 5,
              "careerOpps": 5,
              "benefits": 5,
              "mgmt": 5,
              "total": 5,
              "pros": "This is a great place to get a degree. Community is very supportive and encourages you to learn.",
              "cons": "Winters can be a bit rough being in Chicago, but that's true of every company here.",
              "advice": null,
              "currentEmployee": true,
              "fullTime": true,
              "tenure": ">5",
              "role": "PhD Candidate",
              "locationCity": "Chicago",
              "locationState": "IL",
          },
      ]
  },

    {
      "title": "Tutor Aide",
      "employer": "America Reads",
      "website": "https://www.district65.net/",
      "rating": 3.8,
      "pay": "$13.00/hr",
      "tags": ["Fisk Hall", "Undergrad", "SESP"],
      "hours": null,
      "apply": null,
      "contact": "Anne Horne",
      "email": "a-horne@northwestern.edu",
      "phone": "847-491-8554",
      "description": "Duties include tutoring elementary and middle school students (Evanston District 65), individually or in small groups in reading and/or math; reviewing students' work and offering constructive criticism; helping with homework; being a mentor and positive role model.",
      "qualifications": "Previous experience is preferred but not required. Must be patient, dependable, reliable and enjoy working with children. Students must fill out an America Reads application, available at the Work-Study Office (1801 Hinman, Second Floor). You have to register for classes in order to figure out when you are available to tutor in your free time. A two quarter commitment is expected. Students will be required to commute to their assigned site (1.5 - 3.0 miles from campus) by car, bus, bike, train or walking. One 1/2 hour of travel time (.5) will be paid for each day that a student tutors to cover transportation costs. Students can only be paid for a maximum of 10 total hours per week including travel time.",
      "workStudy": true,
      "onCampus": false,
      "reviews": [
          {
              "id": 1,
              "title": "Fancy from the outside",
              "date": 20190402,
              "recommend": false,
              "outlook": "neutral",
              "ceoOpinion": null,
              "balance": 2,
              "culture": 1,
              "careerOpps": 4,
              "benefits": 3,
              "mgmt": 3,
              "total": 1,
              "pros": "The name alone will get you in the door to other jobs",
              "cons": "Your role, opinion are not valued, pay is low compared to similar institutions. They depend on their name as compensation, but if your a real professional you contribute as much as they do and you should be compensated as such. No diversity, nonfriendly culture throughout every department.",
              "advice": null,
              "currentEmployee": false,
              "fullTime": false,
              "tenure": "<1",
              "role": "Nurse Clinician",
              "locationCity": "Chicago",
              "locationState": "IL",
          },

          {
              "id": 2,
              "title": "Great place to research!",
              "date": 20190404,
              "recommend": true,
              "outlook": "positive",
              "ceoOpinion": null,
              "balance": 5,
              "culture": 5,
              "careerOpps": 5,
              "benefits": 5,
              "mgmt": 5,
              "total": 5,
              "pros": "This is a great place to get a degree. Community is very supportive and encourages you to learn.",
              "cons": "Winters can be a bit rough being in Chicago, but that's true of every company here.",
              "advice": null,
              "currentEmployee": true,
              "fullTime": true,
              "tenure": ">5",
              "role": "PhD Candidate",
              "locationCity": "Chicago",
              "locationState": "IL",
          },
      ]
  },

    {
      "title": "Marketing Assistant",
      "employer": "Rotary International",
      "website": "https://www.rotary.org/en",
      "rating": 1.1,
      "pay": "$13.00/hr",
      "tags": ["Fisk Hall", "Undergrad", "SESP"],
      "hours": "8 to 10",
      "apply": null,
      "contact": "Isabel Price",
      "email": "isabel.price@rotary.org",
      "phone": "847-424-5234",
      "description": "Rotary is an organization of 1.2 million inspired business and professional leaders, in 35,000 Rotary clubs and more than 200 geographical areas united daily across cultures. The Marketing Assistant will learn about the Rotary brand and new public image campaign, People of Action. The Assistant will evaluate story leads sent to the department from Rotary clubs around the world, identifying stories that fit the People of Action narrative to be used in the development of campaign materials.",
      "qualifications": "Knowledge of Microsoft Office is a must. Intermediate experience with Excel is preferred. Writing experience is preferred. Studies in communications, marketing, or international studies is a plus. 4-5 hours a day, two days a week. Schedule is flexible.",
      "workStudy": true,
      "onCampus": false,
      "reviews": [
          {
              "id": 1,
              "title": "Fancy from the outside",
              "date": 20190402,
              "recommend": false,
              "outlook": "neutral",
              "ceoOpinion": null,
              "balance": 2,
              "culture": 1,
              "careerOpps": 4,
              "benefits": 3,
              "mgmt": 3,
              "total": 1,
              "pros": "The name alone will get you in the door to other jobs",
              "cons": "Your role, opinion are not valued, pay is low compared to similar institutions. They depend on their name as compensation, but if your a real professional you contribute as much as they do and you should be compensated as such. No diversity, nonfriendly culture throughout every department.",
              "advice": null,
              "currentEmployee": false,
              "fullTime": false,
              "tenure": "<1",
              "role": "Nurse Clinician",
              "locationCity": "Chicago",
              "locationState": "IL",
          },

          {
              "id": 2,
              "title": "Great place to research!",
              "date": 20190404,
              "recommend": true,
              "outlook": "positive",
              "ceoOpinion": null,
              "balance": 5,
              "culture": 5,
              "careerOpps": 5,
              "benefits": 5,
              "mgmt": 5,
              "total": 5,
              "pros": "This is a great place to get a degree. Community is very supportive and encourages you to learn.",
              "cons": "Winters can be a bit rough being in Chicago, but that's true of every company here.",
              "advice": null,
              "currentEmployee": true,
              "fullTime": true,
              "tenure": ">5",
              "role": "PhD Candidate",
              "locationCity": "Chicago",
              "locationState": "IL",
          },
      ]
  },

  {
    "title": "Career Ambassador",
    "employer": "Northwestern Career Advancement",
    "website": "https://www.northwestern.edu/careers/",
    "rating": 4.1,
    "pay": "$11.00/hr",
    "tags": ["Fisk Hall", "Undergrad", "SESP"],
    "hours": 6,
    "apply": null,
    "contact": "Taylor Kinn",
    "email": "taylor.kinn@northwestern.edu",
    "phone": "847-491-6737",
    "description": "The CA program serves as a bridge between NCA and the NU student population in order to increase awareness of and engagement with NCA’s services and events. CAs serve an integral role at NCA and wear many hats: ambassador, educator, adviser and more!",
    "qualifications": " Sincere desire and commitment to learn and help students; Genuine interest in career related issues. Preferred: Strong communicator; Responsive to emails; Demonstrated ability to take initiative; Willing to ask questions and actively contribute; Friendly and helpful; Presentation skills",
    "workStudy": true,
    "onCampus": true,
    "reviews": [
        {
            "id": 1,
            "title": "Good Place to Work",
            "date": 20190402,
            "recommend": true,
            "outlook": "neutral",
            "ceoOpinion": null,
            "balance": 2,
            "culture": 1,
            "careerOpps": 4,
            "benefits": 3,
            "mgmt": 3,
            "total": 4,
            "pros": "Flexible scheduling for workshops and presentations",
            "cons": "You must be prepared to give presentations on your work every two weeks.",
            "advice": null,
            "currentEmployee": true,
            "fullTime": false,
            "tenure": "<1",
            "role": "Career Advisor",
            "locationCity": "Evanston",
            "locationState": "IL",
        },

        {
            "id": 2,
            "title": "Gets Boring",
            "date": 20190404,
            "recommend": true,
            "outlook": "positive",
            "ceoOpinion": null,
            "balance": 5,
            "culture": 5,
            "careerOpps": 5,
            "benefits": 5,
            "mgmt": 5,
            "total": 2,
            "pros": "It feels good to help others reach their career goals.",
            "cons": "It's basically the same thing every day, and it gets boring after a couple weeks.",
            "advice": null,
            "currentEmployee": true,
            "fullTime": true,
            "tenure": ">5",
            "role": "Career Ambassador",
            "locationCity": "Evanston",
            "locationState": "IL",
        },
    ]
  },
];

class App extends Component {

  constructor(props) {
    super(props);
    this.state = {
      currentPageIndex: 0,
      currentSelectedJob: {},
      currentJobNo: 0
    }
  }

  selectJob = (num, job) => {
    this.setState({currentPageIndex: 1, currentSelectedJob: job, currentJobNo: num});
  }

  selectReviewJob = (job) => {
    this.setState({currentPageIndex: 2, currentSelectedJob: job});
  }

  goBack = () => {
    this.setState({currentPageIndex: this.state.currentPageIndex-1});
  }

  render() {
    switch (this.state.currentPageIndex) {
      case 0:
        return <HomeScreen selectJob={this.selectJob} jobs={JOBS} />
      case 1:
        return <JobScreen job={this.state.currentSelectedJob} goBack={this.goBack} selectReviewJob={this.selectReviewJob}/>
      case 2:
        return <ReviewForm job={this.state.currentSelectedJob} goBack={this.goBack} jobNo={this.state.currentJobNo}/>
      default:
        return <HomeScreen selectJob={this.selectJob} jobs={JOBS} />
    }
  }
}

export default App;
